---
- block:
  - name: get locale file location
    set_fact:
      nakahiro386_locale_file_location: "{{ vars['nakahiro386_locale_file_location_' +  ansible_os_family.lower()] }}"
    check_mode: no
    changed_when: no

  - name: get locale
    command: "cat {{ nakahiro386_locale_file_location }}"
    register: get_locale
    check_mode: no
    changed_when: no
  - set_fact:
      locale_status: "LANG={{ nakahiro386_locale }}"
    check_mode: no
    changed_when: no

  - name: change locale
    command: "update-locale LANG={{ nakahiro386_locale }}"
    when: locale_status not in get_locale.stdout

  - name: get locale
    command: "cat {{ nakahiro386_locale_file_location }}"
    register: get_locale
    check_mode: no
    changed_when: no

  - name: check locale
    assert:
      that:
        - "'LANG={{ nakahiro386_locale }}' in get_locale.stdout "
    when: not ansible_check_mode

  tags:
    - locale
    - config
    - system
