---
# tasks file for nakahiro386.locale
- block:
  - name: Install tools
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items: "{{ nakahiro386_ubuntu_lang_packs }}"
    when: ansible_distribution == 'Ubuntu'

  - name: Ensure a locale exists.
    locale_gen:
      name: "{{ nakahiro386_locale }}"
      state: present
    when:
      - ansible_os_family != 'RedHat'

  - include_tasks: "locale_{{ ansible_os_family.lower() }}.yml"
    when:
      - ansible_service_mgr != 'systemd'

  - include_tasks: locale_systemd.yml
    when: ansible_service_mgr == 'systemd'

  tags:
    - locale
    - config
    - system

